# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-27 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFinished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time_arrived', models.FloatField()),
                ('response_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestRejected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time_arrived', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestToAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_to_accept', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
