# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_requestfinished_requestrejected_requesttoaccept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_to_accept', models.IntegerField()),
                ('submitted', models.IntegerField()),
                ('finished', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('total_time', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='RequestFinished',
        ),
        migrations.DeleteModel(
            name='RequestRejected',
        ),
        migrations.DeleteModel(
            name='RequestSubmitted',
        ),
        migrations.DeleteModel(
            name='RequestToAccept',
        ),
    ]
