# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180502_0840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Tasks_Interval',
        ),
    ]
