# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180502_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_interval',
            name='number_to_accept',
            field=models.IntegerField(default='9223372036854775807'),
        ),
    ]
