# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180507_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_interval',
            name='finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks_interval',
            name='number_to_accept',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AlterField(
            model_name='tasks_interval',
            name='rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks_interval',
            name='submitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasks_interval',
            name='total_time',
            field=models.FloatField(default=0),
        ),
    ]
