# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180507_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_interval',
            name='computation_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tasks_interval',
            name='transmission_time',
            field=models.FloatField(default=0),
        ),
    ]
